package seatingassignment;


import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import static seatingassignment.AccountManager.accounts;
import static seatingassignment.AccountManager.currentAccount;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author az15240
 */
public class GUI extends javax.swing.JFrame {
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createNewAccountFrame = new javax.swing.JFrame();
        createNewAccountLabel = new javax.swing.JLabel();
        usernameNewAccountLabel = new javax.swing.JLabel();
        passwordNewAccountLabel = new javax.swing.JLabel();
        usernameNewAccountTextField = new javax.swing.JTextField();
        passwordNewAccountPasswordField = new javax.swing.JPasswordField();
        createNewAccountButton = new javax.swing.JButton();
        loginFrame = new javax.swing.JFrame();
        loginLabel = new javax.swing.JLabel();
        usernameLoginLabel = new javax.swing.JLabel();
        passwordLoginLabel = new javax.swing.JLabel();
        usernameLoginTextField = new javax.swing.JTextField();
        passwordLoginPasswordField = new javax.swing.JPasswordField();
        confirmLoginButton = new javax.swing.JButton();
        deleteAccountFrame = new javax.swing.JFrame();
        deleteAccountLabel = new javax.swing.JLabel();
        deleteAccountScrollPane = new javax.swing.JScrollPane();
        deleteAccountTextArea = new javax.swing.JTextArea();
        usernameDeleteAccountTextField = new javax.swing.JTextField();
        usernameDeleteAccountLabel = new javax.swing.JLabel();
        passwordDeleteAccountLabel = new javax.swing.JLabel();
        passwordDeleteAccountPasswordField = new javax.swing.JPasswordField();
        confirmDeleteButton = new javax.swing.JButton();
        createNewLayoutFrame = new javax.swing.JFrame();
        createNewLayoutLabel = new javax.swing.JLabel();
        nameNewLayoutLabel = new javax.swing.JLabel();
        numberOfRowsNewLayoutLabel = new javax.swing.JLabel();
        numberOfColumnsNewLayoutLabel = new javax.swing.JLabel();
        numberOfBlocksCanceledNewLayoutLabel = new javax.swing.JLabel();
        nameNewLayoutTextField = new javax.swing.JTextField();
        continueCreateNewLayoutButton = new javax.swing.JButton();
        numberOfRowsNewLayoutSpinner = new javax.swing.JSpinner();
        numberOfColumnsNewLayoutSpinner = new javax.swing.JSpinner();
        numberOfBlocksCanceledNewLayoutSpinner = new javax.swing.JSpinner();
        startAssigningSeatsFrame = new javax.swing.JFrame();
        startAssigningSeatsLabel = new javax.swing.JLabel();
        startAssigningSeatsScrollPane = new javax.swing.JScrollPane();
        startAssigningSeatsTextArea = new javax.swing.JTextArea();
        retryStartAssigningSeatsButton = new javax.swing.JButton();
        confirmStartAssigningSeatsButton = new javax.swing.JButton();
        frontDoorStartAssigningSeatsLabel = new javax.swing.JLabel();
        layoutDisplayFrame = new javax.swing.JFrame();
        layoutDisplayLabel = new javax.swing.JLabel();
        confirmLayoutDisplayButton = new javax.swing.JButton();
        cancelLayoutDisplayButton = new javax.swing.JButton();
        layoutDisplayScrollPane = new javax.swing.JScrollPane();
        layoutDisplayTextArea = new javax.swing.JTextArea();
        ________MeansThereIsASeatLayoutDisplayLabel = new javax.swing.JLabel();
        xxxxxxxxMeansTheSeatIsCanceledLayoutDisplayLabel = new javax.swing.JLabel();
        inputCoordinateCanceledFrame = new javax.swing.JFrame();
        inputCoordinateCanceledLabel = new javax.swing.JLabel();
        rowNumberInputCoordinateCanceledLabel = new javax.swing.JLabel();
        columnNumberInputCoordinateCanceledLabel = new javax.swing.JLabel();
        rowNumberInputCoordinateCanceledTextField = new javax.swing.JTextField();
        columnNumberInputCoordinateCanceledTextField = new javax.swing.JTextField();
        nextInputCoordinateCanceledButton = new javax.swing.JButton();
        chooseYourLayoutFrame = new javax.swing.JFrame();
        chooseYourLayoutLabel = new javax.swing.JLabel();
        chooseYourLayoutScrollPane = new javax.swing.JScrollPane();
        chooseYourLayoutTextArea = new javax.swing.JTextArea();
        yourChoiceChooseYourLayoutLabel = new javax.swing.JLabel();
        yourChoiceChooseYourLayoutTextField = new javax.swing.JTextField();
        confirmChooseYourLayoutButton = new javax.swing.JButton();
        deleteLayoutFrame = new javax.swing.JFrame();
        deleteLayoutLabel = new javax.swing.JLabel();
        deleteLayoutScrollPane = new javax.swing.JScrollPane();
        deleteLayoutTextArea = new javax.swing.JTextArea();
        yourChoiceDeleteLayoutLabel = new javax.swing.JLabel();
        yourChoiceDeleteLayoutTextField = new javax.swing.JTextField();
        confirmDeleteLayoutButton = new javax.swing.JButton();
        setStudentsThatCannotSeatTogetherFrame = new javax.swing.JFrame();
        setStudentsThatCannotSeatTogetherLabel = new javax.swing.JLabel();
        firstStudentNameSetStudentsThatCannotSeatTogetherLabel = new javax.swing.JLabel();
        secondStudentNameSetStudentsThatCannotSeatTogetherLabel = new javax.swing.JLabel();
        setStudentsThatCannotSeatTogetherScrollPane = new javax.swing.JScrollPane();
        setStudentsThatCannotSeatTogetherTextArea = new javax.swing.JTextArea();
        firstStudentNameSetStudentsThatCannotSeatTogetherTextField = new javax.swing.JTextField();
        secondStudentNameSetStudentsThatCannotSeatTogetherTextField = new javax.swing.JTextField();
        setStudentsThatCannotSeatTogetherButton = new javax.swing.JButton();
        deleteStudentsPropertiesFrame = new javax.swing.JFrame();
        deleteStudentsPropertiesLabel = new javax.swing.JLabel();
        deleteStudentsPropertiesScrollPane = new javax.swing.JScrollPane();
        deleteStudentsPropertiesTextArea = new javax.swing.JTextArea();
        confirmDeleteStudentsPropertiesButton = new javax.swing.JButton();
        cancelDeleteStudentsPropertiesButton = new javax.swing.JButton();
        seatingAssignmentLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        developerLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        loginMenu = new javax.swing.JMenu();
        createNewAccountMenuItem = new javax.swing.JMenuItem();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        deleteAccountMenuItem = new javax.swing.JMenuItem();
        layoutsMenu = new javax.swing.JMenu();
        createNewLayoutMenuItem = new javax.swing.JMenuItem();
        deleteLayoutMenuItem = new javax.swing.JMenuItem();
        studentPropertiesMenu = new javax.swing.JMenu();
        editPropertiesMenu = new javax.swing.JMenu();
        addNewPropertiesMenuItem = new javax.swing.JMenuItem();
        deletePropertiesMenuItem = new javax.swing.JMenuItem();
        startAssigningSeatsMenu = new javax.swing.JMenu();
        randomSeatingMenuItem = new javax.swing.JMenuItem();
        newFeaturesMenu = new javax.swing.JMenu();
        checkNewFeaturesMenuItem = new javax.swing.JMenuItem();

        createNewAccountLabel.setFont(createNewAccountLabel.getFont().deriveFont(createNewAccountLabel.getFont().getStyle() | java.awt.Font.BOLD, 18));
        createNewAccountLabel.setText("Create New Account");

        usernameNewAccountLabel.setText("Username");

        passwordNewAccountLabel.setText("Password");

        usernameNewAccountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameNewAccountTextFieldActionPerformed(evt);
            }
        });

        passwordNewAccountPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordNewAccountPasswordFieldActionPerformed(evt);
            }
        });

        createNewAccountButton.setText("Create");
        createNewAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createNewAccountFrameLayout = new javax.swing.GroupLayout(createNewAccountFrame.getContentPane());
        createNewAccountFrame.getContentPane().setLayout(createNewAccountFrameLayout);
        createNewAccountFrameLayout.setHorizontalGroup(
            createNewAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNewAccountFrameLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(createNewAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameNewAccountLabel)
                    .addComponent(passwordNewAccountLabel))
                .addGap(18, 18, 18)
                .addGroup(createNewAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameNewAccountTextField)
                    .addComponent(passwordNewAccountPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addGroup(createNewAccountFrameLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(createNewAccountButton)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createNewAccountFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createNewAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        createNewAccountFrameLayout.setVerticalGroup(
            createNewAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNewAccountFrameLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(createNewAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(createNewAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameNewAccountLabel)
                    .addComponent(usernameNewAccountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(createNewAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordNewAccountLabel)
                    .addComponent(passwordNewAccountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(createNewAccountButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        loginLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        loginLabel.setText("Login");

        usernameLoginLabel.setText("Username");

        passwordLoginLabel.setText("Password");

        passwordLoginPasswordField.setText("123");
        passwordLoginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLoginPasswordFieldActionPerformed(evt);
            }
        });

        confirmLoginButton.setText("Confirm");
        confirmLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginFrameLayout = new javax.swing.GroupLayout(loginFrame.getContentPane());
        loginFrame.getContentPane().setLayout(loginFrameLayout);
        loginFrameLayout.setHorizontalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLoginLabel)
                            .addComponent(passwordLoginLabel))
                        .addGap(50, 50, 50)
                        .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginFrameLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginFrameLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(confirmLoginButton)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        loginFrameLayout.setVerticalGroup(
            loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFrameLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(loginLabel)
                .addGap(65, 65, 65)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLoginLabel)
                    .addComponent(usernameLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(loginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLoginLabel)
                    .addComponent(passwordLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(confirmLoginButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        deleteAccountLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        deleteAccountLabel.setText("Delete an Account");

        deleteAccountTextArea.setEditable(false);
        deleteAccountTextArea.setColumns(20);
        deleteAccountTextArea.setLineWrap(true);
        deleteAccountTextArea.setRows(5);
        deleteAccountTextArea.setText("Displaying all the accounts stored: \n\n<This is the default legacy message. This should not appear in the product. If you see them, then, congratulations! You found a bug! :P>\n\nWhich account do you want to delete? Input the account name and password below.");
        deleteAccountTextArea.setWrapStyleWord(true);
        deleteAccountScrollPane.setViewportView(deleteAccountTextArea);

        usernameDeleteAccountLabel.setText("Account");

        passwordDeleteAccountLabel.setText("Password");

        confirmDeleteButton.setText("Confirm");
        confirmDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteAccountFrameLayout = new javax.swing.GroupLayout(deleteAccountFrame.getContentPane());
        deleteAccountFrame.getContentPane().setLayout(deleteAccountFrameLayout);
        deleteAccountFrameLayout.setHorizontalGroup(
            deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountFrameLayout.createSequentialGroup()
                .addGroup(deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteAccountFrameLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordDeleteAccountLabel)
                            .addComponent(usernameDeleteAccountLabel))
                        .addGap(39, 39, 39)
                        .addGroup(deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameDeleteAccountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordDeleteAccountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmDeleteButton)))
                    .addGroup(deleteAccountFrameLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(deleteAccountLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAccountFrameLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(deleteAccountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        deleteAccountFrameLayout.setVerticalGroup(
            deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAccountFrameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(deleteAccountLabel)
                .addGap(34, 34, 34)
                .addComponent(deleteAccountScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameDeleteAccountLabel)
                    .addComponent(usernameDeleteAccountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(deleteAccountFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordDeleteAccountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordDeleteAccountLabel))
                .addGap(29, 29, 29)
                .addComponent(confirmDeleteButton)
                .addGap(34, 34, 34))
        );

        createNewLayoutLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        createNewLayoutLabel.setText("Create a New Layout");

        nameNewLayoutLabel.setText("Name");

        numberOfRowsNewLayoutLabel.setText("Number of rows");

        numberOfColumnsNewLayoutLabel.setText("Number of columns");

        numberOfBlocksCanceledNewLayoutLabel.setText("Number of blocks canceled");

        nameNewLayoutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameNewLayoutTextFieldActionPerformed(evt);
            }
        });

        continueCreateNewLayoutButton.setText("Continue");
        continueCreateNewLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueCreateNewLayoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createNewLayoutFrameLayout = new javax.swing.GroupLayout(createNewLayoutFrame.getContentPane());
        createNewLayoutFrame.getContentPane().setLayout(createNewLayoutFrameLayout);
        createNewLayoutFrameLayout.setHorizontalGroup(
            createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNewLayoutFrameLayout.createSequentialGroup()
                .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createNewLayoutFrameLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(createNewLayoutLabel))
                    .addGroup(createNewLayoutFrameLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameNewLayoutLabel)
                            .addComponent(numberOfColumnsNewLayoutLabel)
                            .addComponent(numberOfBlocksCanceledNewLayoutLabel)
                            .addComponent(numberOfRowsNewLayoutLabel))
                        .addGap(39, 39, 39)
                        .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameNewLayoutTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numberOfBlocksCanceledNewLayoutSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(numberOfColumnsNewLayoutSpinner)
                                .addComponent(numberOfRowsNewLayoutSpinner, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(88, 88, 88))
            .addGroup(createNewLayoutFrameLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(continueCreateNewLayoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createNewLayoutFrameLayout.setVerticalGroup(
            createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNewLayoutFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(createNewLayoutLabel)
                .addGap(61, 61, 61)
                .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameNewLayoutLabel)
                    .addComponent(nameNewLayoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfRowsNewLayoutLabel)
                    .addComponent(numberOfRowsNewLayoutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfColumnsNewLayoutLabel)
                    .addComponent(numberOfColumnsNewLayoutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createNewLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfBlocksCanceledNewLayoutLabel)
                    .addComponent(numberOfBlocksCanceledNewLayoutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(continueCreateNewLayoutButton)
                .addGap(50, 50, 50))
        );

        startAssigningSeatsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        startAssigningSeatsLabel.setText("Start Assigning Seats");

        startAssigningSeatsTextArea.setEditable(false);
        startAssigningSeatsTextArea.setColumns(20);
        startAssigningSeatsTextArea.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        startAssigningSeatsTextArea.setRows(5);
        startAssigningSeatsTextArea.setWrapStyleWord(true);
        startAssigningSeatsScrollPane.setViewportView(startAssigningSeatsTextArea);

        retryStartAssigningSeatsButton.setText("Retry");
        retryStartAssigningSeatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryStartAssigningSeatsButtonActionPerformed(evt);
            }
        });

        confirmStartAssigningSeatsButton.setText("Confirm");
        confirmStartAssigningSeatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmStartAssigningSeatsButtonActionPerformed(evt);
            }
        });

        frontDoorStartAssigningSeatsLabel.setText("Front door");

        javax.swing.GroupLayout startAssigningSeatsFrameLayout = new javax.swing.GroupLayout(startAssigningSeatsFrame.getContentPane());
        startAssigningSeatsFrame.getContentPane().setLayout(startAssigningSeatsFrameLayout);
        startAssigningSeatsFrameLayout.setHorizontalGroup(
            startAssigningSeatsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startAssigningSeatsFrameLayout.createSequentialGroup()
                .addGroup(startAssigningSeatsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startAssigningSeatsFrameLayout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(frontDoorStartAssigningSeatsLabel))
                    .addGroup(startAssigningSeatsFrameLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(startAssigningSeatsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(startAssigningSeatsFrameLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(retryStartAssigningSeatsButton)
                        .addGap(311, 311, 311)
                        .addComponent(confirmStartAssigningSeatsButton))
                    .addGroup(startAssigningSeatsFrameLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(startAssigningSeatsLabel)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        startAssigningSeatsFrameLayout.setVerticalGroup(
            startAssigningSeatsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startAssigningSeatsFrameLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(startAssigningSeatsLabel)
                .addGap(28, 28, 28)
                .addComponent(frontDoorStartAssigningSeatsLabel)
                .addGap(31, 31, 31)
                .addComponent(startAssigningSeatsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(startAssigningSeatsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retryStartAssigningSeatsButton)
                    .addComponent(confirmStartAssigningSeatsButton))
                .addGap(42, 42, 42))
        );

        layoutDisplayLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        layoutDisplayLabel.setText("Layout Display");

        confirmLayoutDisplayButton.setText("Confirm");
        confirmLayoutDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmLayoutDisplayButtonActionPerformed(evt);
            }
        });

        cancelLayoutDisplayButton.setText("Cancel");
        cancelLayoutDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLayoutDisplayButtonActionPerformed(evt);
            }
        });

        layoutDisplayTextArea.setEditable(false);
        layoutDisplayTextArea.setColumns(20);
        layoutDisplayTextArea.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        layoutDisplayTextArea.setRows(5);
        layoutDisplayTextArea.setWrapStyleWord(true);
        layoutDisplayScrollPane.setViewportView(layoutDisplayTextArea);

        ________MeansThereIsASeatLayoutDisplayLabel.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        ________MeansThereIsASeatLayoutDisplayLabel.setText("________ means there is a seat");

        xxxxxxxxMeansTheSeatIsCanceledLayoutDisplayLabel.setFont(new java.awt.Font("Courier", 0, 13)); // NOI18N
        xxxxxxxxMeansTheSeatIsCanceledLayoutDisplayLabel.setText("xxxxxxxx means the seat is canceled");

        javax.swing.GroupLayout layoutDisplayFrameLayout = new javax.swing.GroupLayout(layoutDisplayFrame.getContentPane());
        layoutDisplayFrame.getContentPane().setLayout(layoutDisplayFrameLayout);
        layoutDisplayFrameLayout.setHorizontalGroup(
            layoutDisplayFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutDisplayFrameLayout.createSequentialGroup()
                .addGroup(layoutDisplayFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layoutDisplayFrameLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(confirmLayoutDisplayButton)
                        .addGap(192, 192, 192)
                        .addComponent(cancelLayoutDisplayButton))
                    .addGroup(layoutDisplayFrameLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(layoutDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layoutDisplayFrameLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layoutDisplayFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xxxxxxxxMeansTheSeatIsCanceledLayoutDisplayLabel)
                            .addComponent(________MeansThereIsASeatLayoutDisplayLabel)))
                    .addGroup(layoutDisplayFrameLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(layoutDisplayLabel)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layoutDisplayFrameLayout.setVerticalGroup(
            layoutDisplayFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutDisplayFrameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(layoutDisplayLabel)
                .addGap(38, 38, 38)
                .addComponent(________MeansThereIsASeatLayoutDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xxxxxxxxMeansTheSeatIsCanceledLayoutDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layoutDisplayFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layoutDisplayFrameLayout.createSequentialGroup()
                        .addComponent(layoutDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layoutDisplayFrameLayout.createSequentialGroup()
                        .addGroup(layoutDisplayFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmLayoutDisplayButton)
                            .addComponent(cancelLayoutDisplayButton))
                        .addGap(36, 36, 36))))
        );

        inputCoordinateCanceledLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        inputCoordinateCanceledLabel.setText("Input 1st coordinate canceled");

        rowNumberInputCoordinateCanceledLabel.setText("Row number");

        columnNumberInputCoordinateCanceledLabel.setText("Column number");

        rowNumberInputCoordinateCanceledTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowNumberInputCoordinateCanceledTextFieldActionPerformed(evt);
            }
        });

        nextInputCoordinateCanceledButton.setText("Next");
        nextInputCoordinateCanceledButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextInputCoordinateCanceledButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputCoordinateCanceledFrameLayout = new javax.swing.GroupLayout(inputCoordinateCanceledFrame.getContentPane());
        inputCoordinateCanceledFrame.getContentPane().setLayout(inputCoordinateCanceledFrameLayout);
        inputCoordinateCanceledFrameLayout.setHorizontalGroup(
            inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputCoordinateCanceledFrameLayout.createSequentialGroup()
                .addGroup(inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inputCoordinateCanceledFrameLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rowNumberInputCoordinateCanceledLabel)
                            .addComponent(columnNumberInputCoordinateCanceledLabel))
                        .addGap(40, 40, 40)
                        .addGroup(inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rowNumberInputCoordinateCanceledTextField)
                            .addComponent(columnNumberInputCoordinateCanceledTextField)))
                    .addGroup(inputCoordinateCanceledFrameLayout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addComponent(inputCoordinateCanceledLabel)))
                .addGap(77, 77, 77))
            .addGroup(inputCoordinateCanceledFrameLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(nextInputCoordinateCanceledButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputCoordinateCanceledFrameLayout.setVerticalGroup(
            inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputCoordinateCanceledFrameLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(inputCoordinateCanceledLabel)
                .addGap(64, 64, 64)
                .addGroup(inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowNumberInputCoordinateCanceledLabel)
                    .addComponent(rowNumberInputCoordinateCanceledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(inputCoordinateCanceledFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(columnNumberInputCoordinateCanceledLabel)
                    .addComponent(columnNumberInputCoordinateCanceledTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(nextInputCoordinateCanceledButton)
                .addGap(43, 43, 43))
        );

        chooseYourLayoutLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        chooseYourLayoutLabel.setText("Choose Your Layout");

        chooseYourLayoutTextArea.setEditable(false);
        chooseYourLayoutTextArea.setColumns(20);
        chooseYourLayoutTextArea.setRows(5);
        chooseYourLayoutTextArea.setText("Current layout options:");
        chooseYourLayoutTextArea.setWrapStyleWord(true);
        chooseYourLayoutScrollPane.setViewportView(chooseYourLayoutTextArea);

        yourChoiceChooseYourLayoutLabel.setText("Your choice: ");

        yourChoiceChooseYourLayoutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourChoiceChooseYourLayoutTextFieldActionPerformed(evt);
            }
        });

        confirmChooseYourLayoutButton.setText("Confirm");
        confirmChooseYourLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChooseYourLayoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseYourLayoutFrameLayout = new javax.swing.GroupLayout(chooseYourLayoutFrame.getContentPane());
        chooseYourLayoutFrame.getContentPane().setLayout(chooseYourLayoutFrameLayout);
        chooseYourLayoutFrameLayout.setHorizontalGroup(
            chooseYourLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseYourLayoutFrameLayout.createSequentialGroup()
                .addGroup(chooseYourLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseYourLayoutFrameLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(chooseYourLayoutLabel))
                    .addGroup(chooseYourLayoutFrameLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(chooseYourLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(chooseYourLayoutFrameLayout.createSequentialGroup()
                                .addComponent(yourChoiceChooseYourLayoutLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yourChoiceChooseYourLayoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chooseYourLayoutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(chooseYourLayoutFrameLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(confirmChooseYourLayoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chooseYourLayoutFrameLayout.setVerticalGroup(
            chooseYourLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseYourLayoutFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(chooseYourLayoutLabel)
                .addGap(31, 31, 31)
                .addComponent(chooseYourLayoutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(chooseYourLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourChoiceChooseYourLayoutLabel)
                    .addComponent(yourChoiceChooseYourLayoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(confirmChooseYourLayoutButton)
                .addGap(44, 44, 44))
        );

        deleteLayoutLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        deleteLayoutLabel.setText("Delete Your Layout");

        deleteLayoutTextArea.setEditable(false);
        deleteLayoutTextArea.setColumns(20);
        deleteLayoutTextArea.setRows(5);
        deleteLayoutTextArea.setText("Current layout options:");
        deleteLayoutTextArea.setWrapStyleWord(true);
        deleteLayoutScrollPane.setViewportView(deleteLayoutTextArea);

        yourChoiceDeleteLayoutLabel.setText("Your choice: ");

        yourChoiceDeleteLayoutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourChoiceDeleteLayoutTextFieldActionPerformed(evt);
            }
        });

        confirmDeleteLayoutButton.setText("Confirm");
        confirmDeleteLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteLayoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteLayoutFrameLayout = new javax.swing.GroupLayout(deleteLayoutFrame.getContentPane());
        deleteLayoutFrame.getContentPane().setLayout(deleteLayoutFrameLayout);
        deleteLayoutFrameLayout.setHorizontalGroup(
            deleteLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayoutFrameLayout.createSequentialGroup()
                .addGroup(deleteLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteLayoutFrameLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(deleteLayoutLabel))
                    .addGroup(deleteLayoutFrameLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(deleteLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(deleteLayoutFrameLayout.createSequentialGroup()
                                .addComponent(yourChoiceDeleteLayoutLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yourChoiceDeleteLayoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteLayoutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deleteLayoutFrameLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(confirmDeleteLayoutButton)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        deleteLayoutFrameLayout.setVerticalGroup(
            deleteLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayoutFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(deleteLayoutLabel)
                .addGap(31, 31, 31)
                .addComponent(deleteLayoutScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(deleteLayoutFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourChoiceDeleteLayoutLabel)
                    .addComponent(yourChoiceDeleteLayoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(confirmDeleteLayoutButton)
                .addGap(44, 44, 44))
        );

        setStudentsThatCannotSeatTogetherLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        setStudentsThatCannotSeatTogetherLabel.setText("Set Students that Cannot Seat Together");

        firstStudentNameSetStudentsThatCannotSeatTogetherLabel.setText("First student name");

        secondStudentNameSetStudentsThatCannotSeatTogetherLabel.setText("Second student name");

        setStudentsThatCannotSeatTogetherTextArea.setEditable(false);
        setStudentsThatCannotSeatTogetherTextArea.setColumns(20);
        setStudentsThatCannotSeatTogetherTextArea.setLineWrap(true);
        setStudentsThatCannotSeatTogetherTextArea.setRows(5);
        setStudentsThatCannotSeatTogetherTextArea.setText("By setting two students to be \"not seating with each other\", their positions are not allowed to be adjacent in the eight directions");
        setStudentsThatCannotSeatTogetherTextArea.setWrapStyleWord(true);
        setStudentsThatCannotSeatTogetherScrollPane.setViewportView(setStudentsThatCannotSeatTogetherTextArea);

        setStudentsThatCannotSeatTogetherButton.setText("Confirm");
        setStudentsThatCannotSeatTogetherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setStudentsThatCannotSeatTogetherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setStudentsThatCannotSeatTogetherFrameLayout = new javax.swing.GroupLayout(setStudentsThatCannotSeatTogetherFrame.getContentPane());
        setStudentsThatCannotSeatTogetherFrame.getContentPane().setLayout(setStudentsThatCannotSeatTogetherFrameLayout);
        setStudentsThatCannotSeatTogetherFrameLayout.setHorizontalGroup(
            setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setStudentsThatCannotSeatTogetherFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setStudentsThatCannotSeatTogetherLabel)
                .addGap(114, 114, 114))
            .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createSequentialGroup()
                .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(setStudentsThatCannotSeatTogetherScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createSequentialGroup()
                                .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstStudentNameSetStudentsThatCannotSeatTogetherLabel)
                                    .addComponent(secondStudentNameSetStudentsThatCannotSeatTogetherLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(secondStudentNameSetStudentsThatCannotSeatTogetherTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(firstStudentNameSetStudentsThatCannotSeatTogetherTextField)))))
                    .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(setStudentsThatCannotSeatTogetherButton)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        setStudentsThatCannotSeatTogetherFrameLayout.setVerticalGroup(
            setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(setStudentsThatCannotSeatTogetherLabel)
                .addGap(32, 32, 32)
                .addComponent(setStudentsThatCannotSeatTogetherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstStudentNameSetStudentsThatCannotSeatTogetherLabel)
                    .addComponent(firstStudentNameSetStudentsThatCannotSeatTogetherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(setStudentsThatCannotSeatTogetherFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondStudentNameSetStudentsThatCannotSeatTogetherLabel)
                    .addComponent(secondStudentNameSetStudentsThatCannotSeatTogetherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(setStudentsThatCannotSeatTogetherButton)
                .addGap(40, 40, 40))
        );

        deleteStudentsPropertiesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        deleteStudentsPropertiesLabel.setText("Delete Students Properties");

        deleteStudentsPropertiesTextArea.setEditable(false);
        deleteStudentsPropertiesTextArea.setColumns(20);
        deleteStudentsPropertiesTextArea.setLineWrap(true);
        deleteStudentsPropertiesTextArea.setRows(5);
        deleteStudentsPropertiesTextArea.setText("If you choose to delete students properties, ALL previous configuration will be deleted.\n\nCurrently this program only supports deleting all properties.");
        deleteStudentsPropertiesTextArea.setWrapStyleWord(true);
        deleteStudentsPropertiesScrollPane.setViewportView(deleteStudentsPropertiesTextArea);

        confirmDeleteStudentsPropertiesButton.setText("Confirm");
        confirmDeleteStudentsPropertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteStudentsPropertiesButtonActionPerformed(evt);
            }
        });

        cancelDeleteStudentsPropertiesButton.setText("Cancel");
        cancelDeleteStudentsPropertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDeleteStudentsPropertiesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteStudentsPropertiesFrameLayout = new javax.swing.GroupLayout(deleteStudentsPropertiesFrame.getContentPane());
        deleteStudentsPropertiesFrame.getContentPane().setLayout(deleteStudentsPropertiesFrameLayout);
        deleteStudentsPropertiesFrameLayout.setHorizontalGroup(
            deleteStudentsPropertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStudentsPropertiesFrameLayout.createSequentialGroup()
                .addGroup(deleteStudentsPropertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteStudentsPropertiesFrameLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(deleteStudentsPropertiesLabel))
                    .addGroup(deleteStudentsPropertiesFrameLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(deleteStudentsPropertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(deleteStudentsPropertiesFrameLayout.createSequentialGroup()
                                .addComponent(confirmDeleteStudentsPropertiesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelDeleteStudentsPropertiesButton))
                            .addComponent(deleteStudentsPropertiesScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        deleteStudentsPropertiesFrameLayout.setVerticalGroup(
            deleteStudentsPropertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStudentsPropertiesFrameLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(deleteStudentsPropertiesLabel)
                .addGap(50, 50, 50)
                .addComponent(deleteStudentsPropertiesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(deleteStudentsPropertiesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmDeleteStudentsPropertiesButton)
                    .addComponent(cancelDeleteStudentsPropertiesButton))
                .addGap(51, 51, 51))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seatingAssignmentLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        seatingAssignmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatingAssignmentLabel.setText("Seating Assignment");

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setText("Welcome :)\n\n\nPlease log in to the system!");
        textArea.setWrapStyleWord(true);
        scrollPane.setViewportView(textArea);

        developerLabel.setText("Developed by az15240");

        loginMenu.setText("Login");

        createNewAccountMenuItem.setText("Create a New Account");
        createNewAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccountMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(createNewAccountMenuItem);

        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(loginMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(logoutMenuItem);

        deleteAccountMenuItem.setText("Delete an Account");
        deleteAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(deleteAccountMenuItem);

        mainMenuBar.add(loginMenu);

        layoutsMenu.setText("Layouts");

        createNewLayoutMenuItem.setText("Create a New Layout");
        createNewLayoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewLayoutMenuItemActionPerformed(evt);
            }
        });
        layoutsMenu.add(createNewLayoutMenuItem);

        deleteLayoutMenuItem.setText("Delete a Layout");
        deleteLayoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLayoutMenuItemActionPerformed(evt);
            }
        });
        layoutsMenu.add(deleteLayoutMenuItem);

        mainMenuBar.add(layoutsMenu);

        studentPropertiesMenu.setText("Student Properties");

        editPropertiesMenu.setText("Edit Properties");

        addNewPropertiesMenuItem.setText("Add New Properties");
        addNewPropertiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPropertiesMenuItemActionPerformed(evt);
            }
        });
        editPropertiesMenu.add(addNewPropertiesMenuItem);

        deletePropertiesMenuItem.setText("Delete Properties");
        deletePropertiesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePropertiesMenuItemActionPerformed(evt);
            }
        });
        editPropertiesMenu.add(deletePropertiesMenuItem);

        studentPropertiesMenu.add(editPropertiesMenu);

        mainMenuBar.add(studentPropertiesMenu);

        startAssigningSeatsMenu.setText("Start Assigning Seats");

        randomSeatingMenuItem.setText("Random Seating");
        randomSeatingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomSeatingMenuItemActionPerformed(evt);
            }
        });
        startAssigningSeatsMenu.add(randomSeatingMenuItem);

        mainMenuBar.add(startAssigningSeatsMenu);

        newFeaturesMenu.setText("New Features");

        checkNewFeaturesMenuItem.setText("Check New Features");
        checkNewFeaturesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNewFeaturesMenuItemActionPerformed(evt);
            }
        });
        newFeaturesMenu.add(checkNewFeaturesMenuItem);

        mainMenuBar.add(newFeaturesMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(developerLabel)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(seatingAssignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(seatingAssignmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(developerLabel)
                .addGap(29, 29, 29)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccountMenuItemActionPerformed
        if(currentAccount!=null) {
            JOptionPane.showMessageDialog(this,"Already have an account!");
            return;
        }
        
        clearTextComponents(createNewAccountFrame);
        createNewAccountFrame.setVisible(true);
        createNewAccountFrame.pack();        
    }//GEN-LAST:event_createNewAccountMenuItemActionPerformed

    private void usernameNewAccountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameNewAccountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameNewAccountTextFieldActionPerformed

    private void passwordNewAccountPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordNewAccountPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordNewAccountPasswordFieldActionPerformed

    private void passwordLoginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLoginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordLoginPasswordFieldActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        if(currentAccount!=null) {
            JOptionPane.showMessageDialog(this,"Already have an account!");
            return;
        }
        
        clearTextComponents(loginFrame);
        loginFrame.setVisible(true);
        loginFrame.pack();                           
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void deleteAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountMenuItemActionPerformed
       if(accounts==null) {
            JOptionPane.showMessageDialog(this,"No account available!");
            return;
        }
        
        if(currentAccount==null) {
            JOptionPane.showMessageDialog(this,"Please login first!");
            return;
        }
        
        clearTextComponents(deleteAccountFrame);
        deleteAccountFrame.setVisible(true);
        deleteAccountFrame.pack();
        
        String str=AccountManager.getAccountsInString();
        deleteAccountTextArea.setText("Displaying all the accounts stored: \n\n"+str+"\n\nWhich account do you want to delete? Input the account name and password below.");
    }//GEN-LAST:event_deleteAccountMenuItemActionPerformed

    private void createNewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccountButtonActionPerformed
        String myUsername = usernameNewAccountTextField.getText().trim();
        char[] myPasswordChar = passwordNewAccountPasswordField.getPassword();
        String myPassword = new String(myPasswordChar);
        
        if(myUsername.equals("") || myPassword.equals("")) {
            usernameNewAccountTextField.setText("");
            passwordNewAccountPasswordField.setText("");
            return;
        }

        for(Account acc:AccountManager.accounts) {
            if(acc.getUsername().equals(myUsername)) {
                JOptionPane.showMessageDialog(createNewAccountFrame, "Account already exist! Create your account again.");
                usernameNewAccountTextField.setText("");
                passwordNewAccountPasswordField.setText("");
                return;
            }
        }

        JOptionPane.showMessageDialog(createNewAccountFrame, "Account successsfully created!\nImport student list at Accounts/"+myUsername+".csv");
        AccountManager.createNewAccount(myUsername,myPassword);
        createNewAccountFrame.dispose();
        
        textArea.setText("Hi, "+currentAccount.getUsername()+"!");
    }//GEN-LAST:event_createNewAccountButtonActionPerformed

    private void confirmLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmLoginButtonActionPerformed
        if(accounts.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please create an account first!");
            return;
        }
        
        String myUsername = usernameLoginTextField.getText().trim();
        char[] myPasswordChar = passwordLoginPasswordField.getPassword();
        String myPassword = new String(myPasswordChar);
        
        if(myUsername.equals("") || myPassword.equals("")) {
            usernameLoginTextField.setText("");
            passwordLoginPasswordField.setText("");
            return;
        }
        
        boolean status = AccountManager.login(myUsername,myPassword);
        if(status==true) {
            JOptionPane.showMessageDialog(loginFrame, "Login Successful!");
            loginFrame.dispose();
            textArea.setText("Hi, "+currentAccount.getUsername()+"!");
            return;
        }
        else {
            JOptionPane.showMessageDialog(loginFrame, "Username and password don't match. Input again.");
            usernameLoginTextField.setText("");
            passwordLoginPasswordField.setText("");
            return;
        }
    }//GEN-LAST:event_confirmLoginButtonActionPerformed

    private void createNewLayoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewLayoutMenuItemActionPerformed
        if(currentAccount==null) {
            JOptionPane.showMessageDialog(this,"Please login first!");
            return;
        }

        clearTextComponents(createNewLayoutFrame);
        createNewLayoutFrame.setVisible(true);
        createNewLayoutFrame.pack();
    }//GEN-LAST:event_createNewLayoutMenuItemActionPerformed

    private void randomSeatingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomSeatingMenuItemActionPerformed
        if(currentAccount==null) {
            JOptionPane.showMessageDialog(this,"Please login first!");
            return;
        }
        
        clearTextComponents(chooseYourLayoutFrame);
        chooseYourLayoutFrame.setVisible(true);
        chooseYourLayoutFrame.pack();   

        students=StudentManager.loadStudentList();
        
        maxLengthOfNames=0;
        for(Student _stu:students) {
            maxLengthOfNames = Math.max(maxLengthOfNames,_stu.getName().length());
        }
        maxLengthOfNames+=2;
        
        String chooseYourLayoutTextAreaText = "Current layout options:\n\n"; 
        chooseYourLayoutTextAreaText += Layout.getLayoutsInString();
        chooseYourLayoutTextArea.setText(chooseYourLayoutTextAreaText);
        
        layouts = Layout.getLayoutsInArrayListLayout();
    }//GEN-LAST:event_randomSeatingMenuItemActionPerformed

    private void checkNewFeaturesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNewFeaturesMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Random Seating is supported.\n\nNow you may assign certain students that cannot seat with each other in \"Student Properties -> Edit Properties\" menu.");
    }//GEN-LAST:event_checkNewFeaturesMenuItemActionPerformed

    private void nameNewLayoutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameNewLayoutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameNewLayoutTextFieldActionPerformed

    private void continueCreateNewLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueCreateNewLayoutButtonActionPerformed
        String _name;
        int row,col,cancelNum;
        _name=nameNewLayoutTextField.getText().trim();
        row=(int) numberOfRowsNewLayoutSpinner.getValue();
        col=(int) numberOfColumnsNewLayoutSpinner.getValue();
        cancelNum=(int) numberOfBlocksCanceledNewLayoutSpinner.getValue();

        if(row<=0 || col<=0 || cancelNum<0) {
            JOptionPane.showMessageDialog(createNewLayoutFrame,"Invalid data. Input again!");
            nameNewLayoutTextField.setText("");
            numberOfRowsNewLayoutSpinner.setValue(0);
            numberOfColumnsNewLayoutSpinner.setValue(0);
            numberOfBlocksCanceledNewLayoutSpinner.setValue(0);
            return;
        }
        currentLayout = new Layout(_name,row,col,cancelNum);

        if(cancelNum!=0) {
            JOptionPane.showMessageDialog(this,"You have selected "+cancelNum+" blocks to cancel. Input their coordinates in a new frame.");
            
            clearTextComponents(inputCoordinateCanceledFrame);
            inputCoordinateCanceledFrame.setVisible(true);
            inputCoordinateCanceledFrame.pack();
            
            createNewLayoutFrame.dispose();
        }
        else {
            clearTextComponents(layoutDisplayFrame);
            layoutDisplayFrame.setVisible(true);
            layoutDisplayFrame.pack();
            
            String layoutDisplayTextAreaText = currentLayout.getMapInString();
            layoutDisplayTextArea.setText(layoutDisplayTextAreaText);
            
            createNewLayoutFrame.dispose();
        }
    }//GEN-LAST:event_continueCreateNewLayoutButtonActionPerformed

    private void confirmDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteButtonActionPerformed
        String myUsername = usernameDeleteAccountTextField.getText().trim();
        char[] myPasswordChar = passwordDeleteAccountPasswordField.getPassword();
        String myPassword = new String(myPasswordChar);
        
        if(myUsername.equals("") || myPassword.equals("")) {
            usernameDeleteAccountTextField.setText("");
            passwordDeleteAccountPasswordField.setText("");
            return;
        }
        
        if(currentAccount.getUsername().equals(myUsername) && currentAccount.getPassword().equals(myPassword)) {
            JOptionPane.showMessageDialog(deleteAccountFrame, "Cannot delete your own account!");
            usernameDeleteAccountTextField.setText("");
            passwordDeleteAccountPasswordField.setText("");
            return;
        }
        
        boolean status = AccountManager.deleteAccount(myUsername, myPassword);
        if(status==true) {
            JOptionPane.showMessageDialog(deleteAccountFrame, "Account "+myUsername+" is canceled");
            
            String deleteAccountTextAreaText = "";
            for(Account acc:accounts) 
                deleteAccountTextAreaText+=acc.getUsername()+", ";
            deleteAccountTextAreaText=deleteAccountTextAreaText.substring(0,deleteAccountTextAreaText.length()-2);
            deleteAccountTextArea.setText("Displaying all the accounts stored: \n\n"+deleteAccountTextAreaText+"\n\nWhich account do you want to delete? Input the account name and password below.");
            return;
        }
        else {
            JOptionPane.showMessageDialog(deleteAccountFrame, "Username and password don't match. Input again.");
            usernameDeleteAccountTextField.setText("");
            passwordDeleteAccountPasswordField.setText("");
            return;
        }
    }//GEN-LAST:event_confirmDeleteButtonActionPerformed

    private void rowNumberInputCoordinateCanceledTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowNumberInputCoordinateCanceledTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowNumberInputCoordinateCanceledTextFieldActionPerformed

    private void nextInputCoordinateCanceledButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextInputCoordinateCanceledButtonActionPerformed
        int _x,_y;
        try {
            _x=Integer.parseInt(rowNumberInputCoordinateCanceledTextField.getText());
            _y=Integer.parseInt(columnNumberInputCoordinateCanceledTextField.getText());    
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(inputCoordinateCanceledFrame,"Invalid number format!");
            rowNumberInputCoordinateCanceledTextField.setText("");
            columnNumberInputCoordinateCanceledTextField.setText("");
            return;
        }
        
        if(_x<1 || _x>currentLayout.getRows() || _y<1 || _y>currentLayout.getColumns()) {
            JOptionPane.showMessageDialog(inputCoordinateCanceledFrame,"Invalid range!");
            rowNumberInputCoordinateCanceledTextField.setText("");
            columnNumberInputCoordinateCanceledTextField.setText("");
            return;
        }
        
        for(Pair _pr:currentLayout.getPositionCanceled()) {
            if(_pr.equals(new Pair(_x,_y))) {
                JOptionPane.showMessageDialog(inputCoordinateCanceledFrame,"Already exist!");
                rowNumberInputCoordinateCanceledTextField.setText("");
                columnNumberInputCoordinateCanceledTextField.setText("");
                return;
            }
        }
        
        currentLayout.addPositionCanceled(_x,_y);
        currentLayout.setMapAtPosition(_x,_y);
        currentLayout.incrementCounter();
        
        String temp=""+currentLayout.getCounter();
        if(currentLayout.getCounter()%10==1) temp+="st";
        else if(currentLayout.getCounter()%10==2) temp+="nd";
        else if(currentLayout.getCounter()%10==3) temp+="rd";
        else temp+="th";
        
        inputCoordinateCanceledLabel.setText("Input "+temp+" coordinate canceled");
        rowNumberInputCoordinateCanceledTextField.setText("");
        columnNumberInputCoordinateCanceledTextField.setText("");
        
        if(currentLayout.getCounter()==currentLayout.getNumberCanceled()+1) {
            currentLayout.setCounter(0);
            JOptionPane.showMessageDialog(inputCoordinateCanceledFrame,"Finished!");
            inputCoordinateCanceledFrame.dispose();
            
            clearTextComponents(layoutDisplayFrame);
            layoutDisplayFrame.setVisible(true);
            layoutDisplayFrame.pack();
            
            String layoutDisplayTextAreaText=currentLayout.getMapInString();
            layoutDisplayTextArea.setText(layoutDisplayTextAreaText);
            
            return;
        }
    }//GEN-LAST:event_nextInputCoordinateCanceledButtonActionPerformed

    private void cancelLayoutDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLayoutDisplayButtonActionPerformed
        JOptionPane.showMessageDialog(layoutDisplayFrame, "Layout canceled!");
        layoutDisplayFrame.dispose();
    }//GEN-LAST:event_cancelLayoutDisplayButtonActionPerformed

    private void confirmLayoutDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmLayoutDisplayButtonActionPerformed
        JOptionPane.showMessageDialog(layoutDisplayFrame, "Layout named "+currentLayout.getName()+" is successfully saved!");
        currentLayout.saveLayout();
        layoutDisplayFrame.dispose();
    }//GEN-LAST:event_confirmLayoutDisplayButtonActionPerformed

    private void yourChoiceChooseYourLayoutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourChoiceChooseYourLayoutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourChoiceChooseYourLayoutTextFieldActionPerformed

    private void confirmChooseYourLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChooseYourLayoutButtonActionPerformed
        //choose a valid layout
        String yourLayoutChoice = null;
        yourLayoutChoice = yourChoiceChooseYourLayoutTextField.getText();
        
        for(Layout myLayout:layouts) {
            if(myLayout.getName().equals(yourLayoutChoice)) {
                String pathName="Accounts/"+currentAccount.getUsername()+"/"+yourLayoutChoice+".txt";
                try {
                    currentLayout=new Layout(new File(pathName));
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                if(students.size()!=currentLayout.getNumberOfSeats()) {
                    JOptionPane.showMessageDialog(chooseYourLayoutFrame, "Student number = "+students.size() + ".\nNumber of seats = "+ currentLayout.getNumberOfSeats() + ".\nNumber of student does not match!");
                    yourChoiceChooseYourLayoutTextField.setText("");
                    return;
                }
                else {
                    JOptionPane.showMessageDialog(chooseYourLayoutFrame, "Success. Your layout is "+yourLayoutChoice+".");

                    clearTextComponents(startAssigningSeatsFrame);
                    startAssigningSeatsFrame.setVisible(true);
                    startAssigningSeatsFrame.pack();
                    
                    //create a new scheme                    
                    currentScheme = new Scheme(currentLayout,students);
                    currentScheme.RandomSeating();
                    startAssigningSeatsTextArea.setText(currentScheme.getOutputText());
                    
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(chooseYourLayoutFrame, "This name is not found! Input again!");
        yourChoiceChooseYourLayoutTextField.setText("");
    }//GEN-LAST:event_confirmChooseYourLayoutButtonActionPerformed

    private void retryStartAssigningSeatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryStartAssigningSeatsButtonActionPerformed
        startAssigningSeatsTextArea.setText("");

        clearTextComponents(startAssigningSeatsFrame);
        startAssigningSeatsFrame.setVisible(true);
        startAssigningSeatsFrame.pack();

        currentScheme.RandomSeating();
        startAssigningSeatsTextArea.setText(currentScheme.getOutputText());
        return;
    }//GEN-LAST:event_retryStartAssigningSeatsButtonActionPerformed

    private void confirmStartAssigningSeatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmStartAssigningSeatsButtonActionPerformed
        JOptionPane.showMessageDialog(startAssigningSeatsFrame, "Seating table saved at Accounts/"+currentAccount.getUsername()+"/seating.csv!");
        currentScheme.saveScheme();
        startAssigningSeatsFrame.dispose();
    }//GEN-LAST:event_confirmStartAssigningSeatsButtonActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        if(currentAccount==null) {
            JOptionPane.showMessageDialog(this, "Please first login!");
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Logout successful!");
        currentAccount=null;
        String textAreaText = "Welcome :)\n" + "\n\n" + "Please log in to the system!";
        textArea.setText(textAreaText);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void deleteLayoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLayoutMenuItemActionPerformed
        if(currentAccount==null) {
            JOptionPane.showMessageDialog(this,"Please login first!");
            return;
        }
        
        clearTextComponents(deleteLayoutFrame);
        deleteLayoutFrame.setVisible(true);
        deleteLayoutFrame.pack();   

        //load the choices of layout
        layouts = Layout.getLayoutsInArrayListLayout();
        String deleteLayoutTextAreaText = "Current layout options:\n\n";
        deleteLayoutTextAreaText+=Layout.getLayoutsInString();
        deleteLayoutTextArea.setText(deleteLayoutTextAreaText);
    }//GEN-LAST:event_deleteLayoutMenuItemActionPerformed

    private void yourChoiceDeleteLayoutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourChoiceDeleteLayoutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourChoiceDeleteLayoutTextFieldActionPerformed

    private void confirmDeleteLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteLayoutButtonActionPerformed
        String yourLayoutChoice = null;
        yourLayoutChoice = yourChoiceDeleteLayoutTextField.getText();
        
        boolean status = Layout.deleteLayout(yourLayoutChoice);
        if(status==true) {
            JOptionPane.showMessageDialog(deleteLayoutFrame, "Layout named "+yourLayoutChoice+" is deleted.");
            yourChoiceDeleteLayoutTextField.setText("");
            
            String deleteLayoutTextAreaText = "Current layout options:\n\n";
            deleteLayoutTextAreaText+=Layout.getLayoutsInString();
            deleteLayoutTextArea.setText(deleteLayoutTextAreaText);
        }
        else {
            JOptionPane.showMessageDialog(deleteLayoutFrame, "This layout is not found! Input again!");
            yourChoiceDeleteLayoutTextField.setText("");
        }
    }//GEN-LAST:event_confirmDeleteLayoutButtonActionPerformed

    private void addNewPropertiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPropertiesMenuItemActionPerformed
        //students=StudentManager.loadStudentList();//not actually useful!?
        
        clearTextComponents(setStudentsThatCannotSeatTogetherFrame);
        setStudentsThatCannotSeatTogetherFrame.setVisible(true);
        setStudentsThatCannotSeatTogetherFrame.pack();
    }//GEN-LAST:event_addNewPropertiesMenuItemActionPerformed

    private void setStudentsThatCannotSeatTogetherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setStudentsThatCannotSeatTogetherButtonActionPerformed
        String studentAName = firstStudentNameSetStudentsThatCannotSeatTogetherTextField.getText();
        String studentBName = secondStudentNameSetStudentsThatCannotSeatTogetherTextField.getText();
        
        boolean status = StudentManager.setCannotSeatTogether(studentAName,studentBName);
        if(status == true) {
            JOptionPane.showMessageDialog(setStudentsThatCannotSeatTogetherFrame, "Success!");
            firstStudentNameSetStudentsThatCannotSeatTogetherTextField.setText("");
            secondStudentNameSetStudentsThatCannotSeatTogetherTextField.setText("");
        }
        else {
            JOptionPane.showMessageDialog(setStudentsThatCannotSeatTogetherFrame, "Invalid process!\nCheck if the two names are correct.");
            firstStudentNameSetStudentsThatCannotSeatTogetherTextField.setText("");
            secondStudentNameSetStudentsThatCannotSeatTogetherTextField.setText("");
        }
    }//GEN-LAST:event_setStudentsThatCannotSeatTogetherButtonActionPerformed

    private void deletePropertiesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePropertiesMenuItemActionPerformed
        clearTextComponents(deleteStudentsPropertiesFrame);
        deleteStudentsPropertiesFrame.setVisible(true);
        deleteStudentsPropertiesFrame.pack();
    }//GEN-LAST:event_deletePropertiesMenuItemActionPerformed

    private void confirmDeleteStudentsPropertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteStudentsPropertiesButtonActionPerformed
        JOptionPane.showMessageDialog(deleteStudentsPropertiesFrame, "Students properties deleted!");
        students=StudentManager.loadStudentList();
        int counter=0;
        for(Student stu:students) {
            stu.setNotSeatWithNumber(counter);
            counter++;
        }
        StudentManager.saveStudentsProperties();
    }//GEN-LAST:event_confirmDeleteStudentsPropertiesButtonActionPerformed

    private void cancelDeleteStudentsPropertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDeleteStudentsPropertiesButtonActionPerformed
        JOptionPane.showMessageDialog(deleteStudentsPropertiesFrame, "Canceled!");
        deleteStudentsPropertiesFrame.dispose();
    }//GEN-LAST:event_cancelDeleteStudentsPropertiesButtonActionPerformed

    /**
     * Fill all empty characters in front of a given String with '0' given the length of the String result
     * @param inputString the String given
     * @param length the length of desired String result
     * @return the String result with all zeros on the left
     */
    public static String padLeftZeros(String inputString, int length) {
        if (inputString.length() >= length) {
            return inputString;
        }
        StringBuilder sb = new StringBuilder();
        while (sb.length() < length - inputString.length()) {
            sb.append(' ');
        }
        sb.append(inputString);
        return sb.toString();
    }
    
    /**
     * Get the maximum length of students' names
     * @return maximum length of students' names
     */
    public int getMaxLengthOfNames() {
        return maxLengthOfNames;
    }
    
    /**
     * Clear all text components in jf
     * @param jf a JFrame to be cleared
     */
    private void clearTextComponents(JFrame jf) {
        for (Component c : jf.getContentPane().getComponents()) {
            if (c instanceof JTextField) {
                ((JTextComponent) c).setText("");
            }
        }
        for (Component c : jf.getComponents()) {
            if (c instanceof JTextArea) {
                ((JTextArea) c).setText("");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    AccountManager.initAccount();
                } catch (Exception ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                new GUI().setVisible(true);
            }
        });
    }
    
    private ArrayList<Student> students;
    private ArrayList<Layout> layouts;
    private Layout currentLayout;
    private Scheme currentScheme;
    public static int maxLengthOfNames;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ________MeansThereIsASeatLayoutDisplayLabel;
    private javax.swing.JMenuItem addNewPropertiesMenuItem;
    private javax.swing.JButton cancelDeleteStudentsPropertiesButton;
    private javax.swing.JButton cancelLayoutDisplayButton;
    private javax.swing.JMenuItem checkNewFeaturesMenuItem;
    private javax.swing.JFrame chooseYourLayoutFrame;
    private javax.swing.JLabel chooseYourLayoutLabel;
    private javax.swing.JScrollPane chooseYourLayoutScrollPane;
    private javax.swing.JTextArea chooseYourLayoutTextArea;
    private javax.swing.JLabel columnNumberInputCoordinateCanceledLabel;
    private javax.swing.JTextField columnNumberInputCoordinateCanceledTextField;
    private javax.swing.JButton confirmChooseYourLayoutButton;
    private javax.swing.JButton confirmDeleteButton;
    private javax.swing.JButton confirmDeleteLayoutButton;
    private javax.swing.JButton confirmDeleteStudentsPropertiesButton;
    private javax.swing.JButton confirmLayoutDisplayButton;
    private javax.swing.JButton confirmLoginButton;
    private javax.swing.JButton confirmStartAssigningSeatsButton;
    private javax.swing.JButton continueCreateNewLayoutButton;
    private javax.swing.JButton createNewAccountButton;
    private javax.swing.JFrame createNewAccountFrame;
    private javax.swing.JLabel createNewAccountLabel;
    private javax.swing.JMenuItem createNewAccountMenuItem;
    private javax.swing.JFrame createNewLayoutFrame;
    private javax.swing.JLabel createNewLayoutLabel;
    private javax.swing.JMenuItem createNewLayoutMenuItem;
    private javax.swing.JFrame deleteAccountFrame;
    private javax.swing.JLabel deleteAccountLabel;
    private javax.swing.JMenuItem deleteAccountMenuItem;
    private javax.swing.JScrollPane deleteAccountScrollPane;
    private javax.swing.JTextArea deleteAccountTextArea;
    private javax.swing.JFrame deleteLayoutFrame;
    private javax.swing.JLabel deleteLayoutLabel;
    private javax.swing.JMenuItem deleteLayoutMenuItem;
    private javax.swing.JScrollPane deleteLayoutScrollPane;
    private javax.swing.JTextArea deleteLayoutTextArea;
    private javax.swing.JMenuItem deletePropertiesMenuItem;
    private javax.swing.JFrame deleteStudentsPropertiesFrame;
    private javax.swing.JLabel deleteStudentsPropertiesLabel;
    private javax.swing.JScrollPane deleteStudentsPropertiesScrollPane;
    private javax.swing.JTextArea deleteStudentsPropertiesTextArea;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JMenu editPropertiesMenu;
    private javax.swing.JLabel firstStudentNameSetStudentsThatCannotSeatTogetherLabel;
    private javax.swing.JTextField firstStudentNameSetStudentsThatCannotSeatTogetherTextField;
    private javax.swing.JLabel frontDoorStartAssigningSeatsLabel;
    private javax.swing.JFrame inputCoordinateCanceledFrame;
    private javax.swing.JLabel inputCoordinateCanceledLabel;
    private javax.swing.JFrame layoutDisplayFrame;
    private javax.swing.JLabel layoutDisplayLabel;
    private javax.swing.JScrollPane layoutDisplayScrollPane;
    private javax.swing.JTextArea layoutDisplayTextArea;
    private javax.swing.JMenu layoutsMenu;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JLabel nameNewLayoutLabel;
    private javax.swing.JTextField nameNewLayoutTextField;
    private javax.swing.JMenu newFeaturesMenu;
    private javax.swing.JButton nextInputCoordinateCanceledButton;
    private javax.swing.JLabel numberOfBlocksCanceledNewLayoutLabel;
    private javax.swing.JSpinner numberOfBlocksCanceledNewLayoutSpinner;
    private javax.swing.JLabel numberOfColumnsNewLayoutLabel;
    private javax.swing.JSpinner numberOfColumnsNewLayoutSpinner;
    private javax.swing.JLabel numberOfRowsNewLayoutLabel;
    private javax.swing.JSpinner numberOfRowsNewLayoutSpinner;
    private javax.swing.JLabel passwordDeleteAccountLabel;
    private javax.swing.JPasswordField passwordDeleteAccountPasswordField;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JPasswordField passwordLoginPasswordField;
    private javax.swing.JLabel passwordNewAccountLabel;
    private javax.swing.JPasswordField passwordNewAccountPasswordField;
    private javax.swing.JMenuItem randomSeatingMenuItem;
    private javax.swing.JButton retryStartAssigningSeatsButton;
    private javax.swing.JLabel rowNumberInputCoordinateCanceledLabel;
    private javax.swing.JTextField rowNumberInputCoordinateCanceledTextField;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel seatingAssignmentLabel;
    private javax.swing.JLabel secondStudentNameSetStudentsThatCannotSeatTogetherLabel;
    private javax.swing.JTextField secondStudentNameSetStudentsThatCannotSeatTogetherTextField;
    private javax.swing.JButton setStudentsThatCannotSeatTogetherButton;
    private javax.swing.JFrame setStudentsThatCannotSeatTogetherFrame;
    private javax.swing.JLabel setStudentsThatCannotSeatTogetherLabel;
    private javax.swing.JScrollPane setStudentsThatCannotSeatTogetherScrollPane;
    private javax.swing.JTextArea setStudentsThatCannotSeatTogetherTextArea;
    private javax.swing.JFrame startAssigningSeatsFrame;
    private javax.swing.JLabel startAssigningSeatsLabel;
    private javax.swing.JMenu startAssigningSeatsMenu;
    private javax.swing.JScrollPane startAssigningSeatsScrollPane;
    private javax.swing.JTextArea startAssigningSeatsTextArea;
    private javax.swing.JMenu studentPropertiesMenu;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel usernameDeleteAccountLabel;
    private javax.swing.JTextField usernameDeleteAccountTextField;
    private javax.swing.JLabel usernameLoginLabel;
    private javax.swing.JTextField usernameLoginTextField;
    private javax.swing.JLabel usernameNewAccountLabel;
    private javax.swing.JTextField usernameNewAccountTextField;
    private javax.swing.JLabel xxxxxxxxMeansTheSeatIsCanceledLayoutDisplayLabel;
    private javax.swing.JLabel yourChoiceChooseYourLayoutLabel;
    private javax.swing.JTextField yourChoiceChooseYourLayoutTextField;
    private javax.swing.JLabel yourChoiceDeleteLayoutLabel;
    private javax.swing.JTextField yourChoiceDeleteLayoutTextField;
    // End of variables declaration//GEN-END:variables
}